---

- hosts: prod
  name: "WebServer Deployment"
  become: yes
  become_method: sudo 
  tasks: 
    - name: Install Required Web Packages
      apt: name=apache2 state=present

    - name: Start APACHE Service
      service: name=apache2 state=started 

- hosts: prod
  name: "Download Mario Image."
  become: yes
  become_method: sudo 
  tasks: 
    - name: Download Required Image
      get_url: url="https://www.mariomayhem.com/downloads/wallpapers/7/nsmb_wp7_1280.jpg" dest=/var/www/html/mario.jpg mode=0755

    - name: Deploy a Sample Site Files
      copy: src=templates/index.j2 dest=/var/www/html/index.html

    - name: Deploy a Sample Site Files
      template: src=templates/info.j2 dest=/var/www/html/info.html
